version: "3.8"

services:

    docker-document-converter:
        container_name: document-converter
        build: .
        command: pdf test.md
        volumes:
            - "./data-local:/media/converter/"
            - "./Readme.md:/media/converter/input/test.md"
